### ISSUE TITLE
Contradicting wiki documentation on ArduCopter 4.0 upgrade for IMX firmware upgrade

### ISSUE THREAD

**Issue by tribbloid** [OpenSolo/OpenSolo#16]
The following page:

https://github.com/OpenSolo/OpenSolo/wiki/Install-via-SSH

gave instructions for upgrading both firmware and ArduCopter to the latest versions. One paragraph in it stated:

> If you are upgrading a stock cube that still has the old 3DR 1.3.2 or 1.5.4 ArduCopter firmware, you need to install ArduCopter 4.0 first! The old firmware is so old, it will not play nicely during the full IMX update, so we need to do it separately first. Visit the [ArduCopter Firmware](https://github.com/OpenSolo/OpenSolo/wiki/ArduCopter-Firmware) for instructions.

Unfortunately, the link leads to a page where the phrase "ArduCopter 4.0" or even the version number "4.0" DOES NOT exist. In addition, The page also stated that ArduCopter-Solo v1.5.4 is already the latest version:

> Open Solo 3.0.0 Release contains binaries specifically for the solo as used in Open Solo 3.0.0, with all the default parameters baked in. This includes ArduCopter-Solo v1.5.4 for the stock cube, and 3.5.4 for the Green Cube.

May I suspect that the link is now obsolete, and a new, more detailed paragraph is required for the intended "ArduCopter 4.0" upgrade?

**Comment by davidbuzz** [comment]
PRs welcome

**Comment by tribbloid** [comment]
I'm not sure if GitHub support forking of wiki. So I'll just post my intended change here, if you have write permission to the wiki, could you help me reviewing and paste it?

## Original:

```
----
=== ArduCopter 3.7 (''Development Beta'')===
'''ArduCopter 3.7 will be fully compatible with all Solos, whether you are totally stock or green cubed.'''  There will no longer be a requirement for different firmware versions.  All users will get all features and benefits of the latest and greatest ArduCopter firmware.

Beta testing of ArduCopter 3.7 is currently in progress in the [https://www.facebook.com/groups/617648671719759 Solo Beta Test Facebook Group.]

''Note: Older versions of ArduCopter used old NuttX RTOS based firmware and a <code>*.px4</code> file extension.  This includes the ArduCopter versions included in Open Solo 3 and from 3DR.  ArduCopter 3.7 uses the new ChibiOS RTOS. The firmware files have a file extension of <code>*.apj</code>.  Due to the file extension change, the firmware will not load without some additional file changes.  The beta testing packages in Solex and SidePilot include this''

The upcoming Open Solo 4 will include ArduCopter 3.7 fully compatible with all Solos, marking a huge milestone for the Solo and Open Solo community.
----
``` 

## Changed:

```
----
=== ArduCopter 4.0+ (''Formerly ArduCopter 3.7-dev'')===
'''ArduCopter 4.0.x will be fully compatible with all Solos, whether you are totally stock or green cubed.'''  There will no longer be a requirement for different firmware versions.  All users will get all features and benefits of the latest and greatest ArduCopter firmware.

Beta testing of ArduCopter 4.0.x/3.7-dev is currently in progress in the [https://www.facebook.com/groups/617648671719759 Solo Beta Test Facebook Group.]

''Note: Older versions of ArduCopter used old NuttX RTOS based firmware and a <code>*.px4</code> file extension.  This includes the ArduCopter versions included in Open Solo 3 and from 3DR.  ArduCopter 4.0.x uses the new ChibiOS RTOS. The firmware files have a file extension of <code>*.apj</code>.  Due to the file extension change, the firmware will not load without some additional file changes.  The beta testing packages in Solex and SidePilot include this''

The Open Solo 4 will include ArduCopter 4.0.x fully compatible with all Solos, marking a huge milestone for the Solo and Open Solo community.

In most cases with Open Solo 4 and/or Solex/SidePilot, installation of ArduCopter 4.0.x will be fully automatic. Manual SSH-based upgrade to ArduCopter 4.0.x is only necessary if you are upgrading a stock cube that still has the old 3DR 1.3.2 or 1.5.4 ArduCopter firmware.
----
``` 

## Original:

```
* [https://github.com/Pedals2Paddles/OpenSolo/releases/tag/OpenSolo-3.0.0 Open Solo 3.0.0 Release] contains binaries specifically for the solo as used in Open Solo 3.0.0, with all the default parameters baked in. This includes ArduCopter-Solo v1.5.4 for the stock cube, and 3.5.4 for the Green Cube.
```

## Changed:

```
* [https://github.com/OpenSolo/OpenSolo/releases/tag/OpenSolo-4.0.0 Open Solo 4 Release] contains binaries specifically for the solo as used in Open Solo 4, with all the default parameters baked in. This includes ArduCopter-Solo v4.0.0 for all versions CubePilot.
* [https://github.com/OpenSolo/OpenSolo/releases/tag/OpenSolo-3.0.0 Open Solo 3.0.0 Release] contains binaries specifically for the solo as used in Open Solo 3.0.0, with all the default parameters baked in. This includes ArduCopter-Solo v1.5.4 for the stock cube, and 3.5.4 for the Green Cube.
```

**Comment by tribbloid** [comment]
No idea how that link to a forked repo skipped all the eyeballs for so long

**Comment by tribbloid** [comment]
Also, why this wiki doesn't contain info regarding pixhawk.py and uploader.py?

https://3drpilots.com/threads/update-1-3-1-to-open-solo-4-dev-via-ssh-sftp.15379/

**Comment by davidbuzz** [comment]
the documentation is trivial to fix....   open a PR, get it reviewed, done.

**Comment by Solo-Loco** [comment]
Gents,

Have been absent from Drones for a couple of years, only to discover just how impressive you guys have been, regarding keeping all of our Solos well-clear from destination 'Landfill'.

Dramas encountered when blowing the dust off of a bone-stock, factory original Solo and Controller, and attempting an update to OpenSolo via SSH - when following the instructions located currently up on the Wiki.

Opened a topic over on ArduPilot - ( [see here](https://discuss.ardupilot.org/t/upgrading-a-3dr-solo-to-opensolo-all-via-ssh-but-with-a-few-dramas/101877) ) - but thought it wise to seek counsel from the legends themselves, as well, eh?

Short-form of the dramas encountered, as follows ;

1) Instructions currently on the Wiki for SSH-upgrade, ( [see here](https://github.com/OpenSolo/OpenSolo/wiki/Install-via-SSH) ), present the first caveat -
_'If you are upgrading a stock cube that still has the old 3DR 1.3.2 or 1.5.4 ArduCopter firmware, **you need to install ArduCopter 4.0 first!** The old firmware is so old, it will not play nicely during the full IMX update, so we need to do it separately first. Visit the [ArduCopter Firmware](https://github.com/OpenSolo/OpenSolo/wiki/ArduCopter-Firmware) for instructions.'_

2) Moving across to the ArduCopter Firmware Page, reveals the problem at hand -
_'Note: Older versions of ArduCopter used old NuttX RTOS based firmware and a *.px4 file extension. This includes the ArduCopter versions included in Open Solo 3 and from 3DR. ArduCopter 3.7 uses the new ChibiOS RTOS. The firmware files have a file extension of *.apj. **Due to the file extension change, the firmware will not load without some additional file changes.** The beta testing packages in Solex and SidePilot include this'_

Any attempt to simply SSH the provided OpenSolo 'arducopter.apj' firmware into the prescribed location - inside a bone-stock, factory original Solo - results with the Solo simply deleting the file upon reboot...

Would love to know what the 'additional file changes' are, ( which Solex and SidePilot use to otherwise perform this upgrade ), and would be thrilled to update the Wiki with this information to assist others.

Warmest Regards,

Solo-Loco
( and Matt, I'm THRILLED to see that you're still here too! )

**Comment by Solo-Loco** [comment]
Yep,

Just found Matt's conversation, concerning this very issue, over on 3drpilots.com - ( [see here](https://3drpilots.com/threads/update-1-3-1-to-open-solo-4-dev-via-ssh-sftp.15379/) )

Carefully read through the entire 'revised' process, and Boom-goes-the-Dynamite - my Solo and associated Controller are now fully OpenSolo-4-o-fied!

Extremely impressed just how far you guys have brought this along - Take a bow, each and every single one of you, as this truly is a gift from above...

In any case, I'm going to submit for consideration the revision for the Wiki via a PR, as I feel that it's the least I can do.


Many thanks -

Solo-Loco.
(c;=

**Comment by davidbuzz** [comment]
Please open a PR when u have improvement/s
